### PR TITLE
Tooling

### PR DESCRIPTION
**Pull request by nickmccurdy**
- Set up Travis. Note that this repository needs to be manually enabled on https://travis-ci.org/
- Add badges
- Tweak package.json metadata and scripts
- Use Redux's prettier and eslint configs
- Format source files and readme examples to be consistent with Redux

### CODE REVIEW

**Comment by nickmccurdy** [comment]
I reworked this to include ESLint, Prettier, and some package.json tweaks.

**Comment by nickmccurdy** [comment]
I made a few tweaks to our Rollup settings to fix warnings and use recommended settings from their docs. This is my first time with Rollup so could someone please sanity check my changes?

**Comment by nickmccurdy** [comment]
I realize this PR was a bit huge, would it be easier to review if I split it up into one for prettier and the unrelated changes?

**Comment by markerikson** [comment]
Haven't had much time to look at this since I published it, to be honest :)

But yeah, let's split these up into isolated PRs, if you could.

**Comment by nickmccurdy** [comment]
I split this up into #20, #21, and #22. Sorry for the mess.

**Pull request closed without merging**
